### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by nd4** [dustyroo/Afk-Credit-Bot#2]
When I opened the game and the countdown from cmd is over(to 1), nothing happened in my screen(pubg is opened), any idea? I played in fullscreen(windowed)

**Comment by dustyroo** [comment]
what screen res did you pick?

**Comment by nd4** [comment]
1366x768 bcs i dont have 1920x1080 monitor

**Comment by dustyroo** [comment]
do you have 1440, 720?

**Comment by nd4** [comment]
Yes

**Comment by nd4** [comment]
I need to set my ress to 1366x768 for make it work ya?

**Comment by dustyroo** [comment]
you will need to set it to 1440 or 720 a weird res like that won't work.
