### ISSUE TITLE
Bot stops eventually after 300 BP

### ISSUE THREAD

**Issue by ayronika** [dustyroo/Afk-Credit-Bot#6]
The bot at first works very well. Then when it hits 300 Battle Points it suddenly stops. 

![23769971_1516989638366164_446681351_o](https://user-images.githubusercontent.com/10159299/33021090-b1c4a2dc-ce11-11e7-859c-df8fc3368bbd.jpg)

**Comment by dustyroo** [comment]
I will look into this. What region are you from?
