### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by Cleeez** [dustyroo/Afk-Credit-Bot#8]
You could at the very least give me credit for this, you even copied my old readme from near the beginning of the month word for word and changed a few variables like the paypal line. 

I'm all for sharing my work but when I see "100% done myself" in the same project you forked from me is a bit confusing.

**Comment by dustyroo** [comment]
It is 100% done by me. Where have I used your work, I check yours and you do a lot different. This is my first project in python and I did use you read me as a template I'll give you that and you did inspire me to do this after you stopped updating your project and claims that you put a coin based miner in your bot. There is not 100% proof of this and your stuff has been removed from 2 hacking sites and people have put in pictures it being in your bot. Also, when I asked you, you removed my comment.

**Comment by Clintoxen** [comment]
Actually i responded and you never responded back to me, I clear the channel periodically. Also I havent posted this on a hacking site yet, gonna post to mpgh soon. Anyway It was weird to see my readme almost word for word. Either way its a cool project you have heard

**Comment by dustyroo** [comment]
what is this?
Log
AfkBot.1.07.zip » ZIP » AfkBot 1.07/tcl/ztdata/Canada/decpreciated/old/CrashReporter.exe - a variant of Win64/BitCoinMiner.CI 


also found that it installed CrashReporter on my pc

**Comment by dustyroo** [comment]
you also keep removing me from the discord.

**Comment by dustyroo** [comment]
I want people to see this, dont close it. Proves you are more guilty

**Comment by Cleeez** [comment]
Actually i don't feel like arguing on the internet. Do what you want, your rebased python bot didn't appear until after you forked mine. If you say that you did it 100% yourself then ok. I really didn't open this issue to start drama but it seems you want some. Have fun

**Comment by dustyroo** [comment]
It installs CrashReporter to 3 directories, why?
